version: '3.8'
services:
  mysql_db:
    image: 'mysql'
    volumes:
      - data:/var/lib/mysql
    # environment:
      # - name=value
      # name:value
    env_file:
      - ./env/mysqlconf.env
  backend:
    # build: ./backend
    build: ./backend
    ports: 
      - '80:8080'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mysql_db
  frontend:
    build: ./frontend
    ports: 
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
volumes:
  data: